// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.migrationsApplied", 12);
user_pref("app.shield.optoutstudies.enabled", false);
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1691793059);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1691793059);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1691793059);
user_pref("app.update.lastUpdateTime.region-update-timer", 1691793059);
user_pref("app.update.lastUpdateTime.rs-experiment-loader-timer", 1691793059);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1691793059);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1691793089);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1691793059);
user_pref("browser.bookmarks.editDialog.confirmationHintShowCount", 1);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contextual-services.contextId", "{53c8eb83-e83a-4945-b26d-afa32c19e0cb}");
user_pref("browser.download.viewableInternally.typeWasRegistered.avif", true);
user_pref("browser.download.viewableInternally.typeWasRegistered.webp", true);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1691793029);
user_pref("browser.laterrun.bookkeeping.sessionCount", 7);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 137);
user_pref("browser.newtabpage.activity-stream.impressionId", "{56277159-9a5f-49b9-b0ae-a86e16743908}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "google");
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://google.com\",\"label\":\"@google\",\"searchTopSite\":true},{\"url\":\"http://mtnbroadband.ng/index.html\",\"label\":\"mtnbroadband\"},{\"url\":\"https://www.duckduckgo.com/\",\"label\":\"Duckduckgo\"},{\"url\":\"https://www.youtube.com/\",\"label\":\"YouTube\"}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"ids\":[\"bookmark\",\"firefox-translations-addon_mozilla_org\"],\"idsInUrlbar\":[\"firefox-translations-addon_mozilla_org\",\"bookmark\"],\"idsInUrlbarPreProton\":[],\"version\":1}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.proton.toolbar.version", 3);
user_pref("browser.sessionstore.upgradeBackup.latestBuildID", "20230807140633");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1691794419");
user_pref("browser.startup.couldRestoreSession.count", 2);
user_pref("browser.startup.homepage", "about:home");
user_pref("browser.startup.homepage_override.buildID", "20230807140633");
user_pref("browser.startup.homepage_override.mstone", "116.0.2");
user_pref("browser.startup.lastColdStartupCheck", 1691794419);
user_pref("browser.toolbars.bookmarks.visibility", "always");
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"unified-extensions-area\":[\"_ddc359d1-844a-42a7-9aa1-88a850a938a8_-browser-action\",\"authenticator_mymindstorm-browser-action\",\"_2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c_-browser-action\",\"jid1-qofqdk4qzufgwq_jetpack-browser-action\",\"firefox-translations-addon_mozilla_org-browser-action\"],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"save-to-pocket-button\",\"downloads-button\",\"fxa-toolbar-menu-button\",\"unified-extensions-button\",\"ublock0_raymondhill_net-browser-action\",\"_531906d3-e22f-4a6c-a102-8057b88a1a63_-browser-action\",\"_9350bc42-47fb-4598-ae0f-825e3dd9ceba_-browser-action\",\"addon_darkreader_org-browser-action\",\"browser-mon_xdman_sourceforge_net-browser-action\",\"_b9db16a4-6edc-47ec-a1f4-b86292ed211d_-browser-action\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"firefox-view-button\",\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"save-to-pocket-button\",\"developer-button\",\"_531906d3-e22f-4a6c-a102-8057b88a1a63_-browser-action\",\"_9350bc42-47fb-4598-ae0f-825e3dd9ceba_-browser-action\",\"addon_darkreader_org-browser-action\",\"ublock0_raymondhill_net-browser-action\",\"browser-mon_xdman_sourceforge_net-browser-action\",\"_ddc359d1-844a-42a7-9aa1-88a850a938a8_-browser-action\",\"_b9db16a4-6edc-47ec-a1f4-b86292ed211d_-browser-action\",\"_2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c_-browser-action\",\"jid1-qofqdk4qzufgwq_jetpack-browser-action\",\"firefox-translations-addon_mozilla_org-browser-action\",\"authenticator_mymindstorm-browser-action\"],\"dirtyAreaCache\":[\"nav-bar\",\"unified-extensions-area\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":19,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "DuckDuckGo");
user_pref("browser.urlbar.placeholderName.private", "DuckDuckGo");
user_pref("browser.urlbar.quicksuggest.migrationVersion", 2);
user_pref("browser.urlbar.quicksuggest.scenario", "history");
user_pref("datareporting.healthreport.uploadEnabled", false);
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1691793031137");
user_pref("devtools.webextensions.{531906d3-e22f-4a6c-a102-8057b88a1a63}.enabled", true);
user_pref("distribution.Manjaro.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "116.0.2");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.forms.autocomplete.formautofill", true);
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.pingCountVersion", 0);
user_pref("extensions.databaseSchema", 35);
user_pref("extensions.getAddons.cache.lastUpdate", 1691793059);
user_pref("extensions.getAddons.databaseSchema", 6);
user_pref("extensions.lastAppBuildId", "20230807140633");
user_pref("extensions.lastAppVersion", "116.0.2");
user_pref("extensions.lastPlatformVersion", "116.0.2");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.pictureinpicture.enable_picture_in_picture_overrides", true);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"addons\":{}}");
user_pref("extensions.ui.dictionary.hidden", true);
user_pref("extensions.ui.extension.hidden", false);
user_pref("extensions.ui.lastCategory", "addons://list/extension");
user_pref("extensions.ui.locale.hidden", true);
user_pref("extensions.ui.sitepermission.hidden", true);
user_pref("extensions.webcompat.enable_shims", true);
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.addon@darkreader.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.authenticator@mymindstorm", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.firefox-translations-addon@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.jid1-QoFqdK4qzUfGWQ@jetpack", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.screenshots@mozilla.org", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.uBlock0@raymondhill.net", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{4a313247-8330-4a81-948e-b79936516f78}", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{531906d3-e22f-4a6c-a102-8057b88a1a63}", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{9350bc42-47fb-4598-ae0f-825e3dd9ceba}", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{DDC359D1-844A-42a7-9AA1-88A850A938A8}", true);
user_pref("extensions.webextensions.ExtensionStorageIDB.migrated.{b9db16a4-6edc-47ec-a1f4-b86292ed211d}", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"56bdd21e-d7e1-4ace-a3ad-8204667d23a5\",\"pictureinpicture@mozilla.org\":\"9bb89eff-7675-4662-9871-ac8028d75713\",\"screenshots@mozilla.org\":\"f8f714ec-24ad-44c8-94fe-c523b8cfc42c\",\"webcompat-reporter@mozilla.org\":\"bae3a596-22a1-4a7d-b10a-ebbc762d3f5c\",\"webcompat@mozilla.org\":\"223744f9-ef91-4241-a617-a4efa1d3303c\",\"default-theme@mozilla.org\":\"86a8f75e-238e-4665-bd98-480769c7c7c1\",\"addons-search-detection@mozilla.com\":\"02d3b4c2-0d42-4d30-9679-2db1576500dc\",\"google@search.mozilla.org\":\"ce3bc16f-1b16-48be-8032-253a5c5ec30b\",\"amazondotcom@search.mozilla.org\":\"54ffd8ac-017b-4c43-b7ed-b6592824df06\",\"wikipedia@search.mozilla.org\":\"ef0b9e5d-cde9-47a6-9ec9-d5bdb07a1454\",\"bing@search.mozilla.org\":\"ff978241-e44e-48ed-9dee-c922d079e0d0\",\"ddg@search.mozilla.org\":\"9e1473fd-8b5c-43a8-a82a-422c9594c39d\",\"{531906d3-e22f-4a6c-a102-8057b88a1a63}\":\"de05e5b0-cb80-4702-866a-ca5cfdc0ab0f\",\"{9350bc42-47fb-4598-ae0f-825e3dd9ceba}\":\"99524dde-f408-4fe8-b89b-dcd596419f42\",\"addon@darkreader.org\":\"56799e78-799e-49b2-975f-4a6cc5b23304\",\"uBlock0@raymondhill.net\":\"a87e9e9f-fccd-436c-a49d-7679eb82b0ff\",\"browser-mon@xdman.sourceforge.net\":\"dc132347-f2c1-4a41-be0d-2b4c8d687b77\",\"{DDC359D1-844A-42a7-9AA1-88A850A938A8}\":\"2d82adc4-cf99-46d6-a438-9f7eaf6d4b67\",\"{b9db16a4-6edc-47ec-a1f4-b86292ed211d}\":\"34ed70e1-6c09-4b15-9960-03c336d4aaa8\",\"{4a313247-8330-4a81-948e-b79936516f78}\":\"229d76f1-1b60-4ad3-b498-7485df381c7c\",\"{2e5ff8c8-32fe-46d0-9fc8-6b8986621f3c}\":\"d2bebf63-386a-4934-97e4-ac548bb8138a\",\"jid1-QoFqdK4qzUfGWQ@jetpack\":\"8867952c-826c-435d-b047-c9183e78c187\",\"firefox-translations-addon@mozilla.org\":\"49f43169-9e8b-4d2c-868f-9d5aa909cc53\",\"authenticator@mymindstorm\":\"f2b222a9-d322-4d12-ac65-6005a5296c0f\"}");
user_pref("gecko.handlerService.defaultHandlersVersion", 1);
user_pref("media.gmp-gmpopenh264.lastDownloadFailReason", "Error: Failed downloading via ServiceRequest, status: 0, channelStatus: 2152398878, errorCode: 2, reason: error");
user_pref("media.gmp-gmpopenh264.lastDownloadFailed", 1691793059);
user_pref("media.gmp-gmpopenh264.lastInstallStart", 1691793059);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.dns.disablePrefetch", true);
user_pref("network.http.speculative-parallel-limit", 0);
user_pref("network.predictor.enabled", false);
user_pref("network.prefetch-next", false);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("privacy.sanitize.pending", "[]");
user_pref("security.sandbox.content.tempDirSuffix", "a1885ac2-7389-40e2-913f-7e3052a5f771");
user_pref("services.sync.clients.lastSync", "0");
user_pref("services.sync.declinedEngines", "");
user_pref("services.sync.engine.addresses.available", true);
user_pref("services.sync.globalScore", 0);
user_pref("services.sync.nextSync", 0);
user_pref("toolkit.startup.last_success", 1691794418);
user_pref("toolkit.telemetry.cachedClientID", "c0ffeec0-ffee-c0ff-eec0-ffeec0ffeec0");
user_pref("toolkit.telemetry.previousBuildID", "20230807140633");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
