[Audio]
Volume=100

[General]
ColorScheme=Kvantum
FloatingFooterTrigger=BottomMouseMovement
SeekMediumStep=5
ShowHeader=false
ShowPreviewThumbnail=true
Volume=100

[Mouse]
Left=
Middle=playPauseAction
Middlex2=
Right=openContextMenuAction
ScrollDown=seekBackwardSmallAction
ScrollUp=seekForwardSmallAction

[Playback]
HWDecoding=no
PlayOnResume=true
RestoreFilePosition=true
SeekToLastPosition=true

[Playlist]
OpenWithSingleClick=true
ShowMediaTitle=false
